In [1]:
import pandas as pd
import csv
import datetime

In [2]:
tvshows_df = pd.read_csv("Data/tvtimeshows.csv")
tvshows_df

,id,name,followers,nb_rates,runtime,number_of_seasons,network,mean_rate,poster_image,seasons
0,288128,X-Ray & Vav,230,10,9,2,Rooster Teeth,4.20,https://dg31sz3gwrwan.cloudfront.net/poster/28...,"[{'number': 1, 'nb_episodes': 4}, {'number': 2..."
1,313803,Sister's Slam Dunk,1298,100,80,2,KBS TV2,4.25,https://dg31sz3gwrwan.cloudfront.net/poster/31...,"[{'number': 1, 'nb_episodes': 33}, {'number': ..."
2,325462,Reverse,270,15,60,1,Tokyo Broadcasting System,4.63,https://dg31sz3gwrwan.cloudfront.net/poster/32...,"[{'number': 1, 'nb_episodes': 10}]"
3,325198,Frame Arms Girl,900,24,25,1,Tokyo MX,3.54,https://dg31sz3gwrwan.cloudfront.net/poster/32...,"[{'number': 1, 'nb_episodes': 12}]"
4,349743,Mr Inbetween,7123,118,25,2,FX,4.42,https://dg31sz3gwrwan.cloudfront.net/poster/34...,"[{'number': 1, 'nb_episodes': 6}, {'number': 2..."
...,...,...,...,...,...,...,...,...,...,...
19811,344220,Umamusume: Pretty Derby,2412,68,25,1,Tokyo MX,4.51,https://dg31sz3gwrwan.cloudfront.net/poster/34...,"[{'number': 1, 'nb_episodes': 13}]"
19812,72470,Hand Maid May,190,5,25,1,WOWOW,3.56,https://dg31sz3gwrwan.cloudfront.net/poster/72...,"[{'number': 1, 'nb_episodes': 10}]"
19813,316950,Stasera tutto è possibile,972,34,130,5,Rai 2,4.27,https://dg31sz3gwrwan.cloudfront.net/poster/31...,"[{'number': 1, 'nb_episodes': 6}, {'number': 2..."
19814,206331,Fire Emblem,251,19,30,1,CBS,3.72,https://dg31sz3gwrwan.cloudfront.net/poster/20...,"[{'number': 1, 'nb_episodes': 2}]"
19815,355431,YG Treasure Box,2853,13,45,1,V LIVE,4.75,https://dg31sz3gwrwan.cloudfront.net/poster/35...,"[{'number': 1, 'nb_episodes': 10}]"

In [3]:
tvshows_df["network"].value_counts().head(20)

YouTube                      715
Netflix                      656
Tokyo MX                     540
ABC (US)                     495
TV Tokyo                     451
NBC                          429
BBC One                      405
CBS                          393
Fuji TV                      336
FOX                          288
Rede Globo                   284
AT-X                         242
MBC                          236
Tokyo Broadcasting System    234
Channel 4                    228
BBC Two                      220
TVN                          192
SBS (KR)                     185
HBO                          179
KBS TV2                      177
Name: network, dtype: int64

In [4]:
episode_df = pd.read_csv("Data/all_episodes.csv")
episode_df

,show_id,episode_id,time,episode,title,description,rating,times_watched,mood-good,mood-fun,mood-wow,mood-sad,mood-so-so,mood-bad
0,315103,5697528,2016-10-05T03:00,S01E01,Idiots with Numbers!,Idiots with Numbers! (S01E01) is the first epi...,9.48,12307.0,175.0,388.0,136.0,1.0,16.0,3.0
1,315103,5774664,2016-10-12T03:00,S01E02,The Inmates Are Stupid! The Guards Are Kind of...,The Inmates Are Stupid! The Guards Are Kind of...,9.52,11423.0,156.0,349.0,82.0,0.0,5.0,3.0
2,315103,5774665,2016-10-19T03:00,S01E03,Another Idiot Has Come!!,Another Idiot Has Come!! (S01E03) is the third...,9.36,11067.0,145.0,339.0,63.0,0.0,7.0,1.0
3,315103,5774666,2016-10-26T03:00,S01E04,Happy New Year! The New Year's Tournament Is W...,Happy New Year! The New Year's Tournament Is W...,8.36,10552.0,134.0,270.0,109.0,0.0,3.0,3.0
4,315103,5774667,2016-11-02T03:00,S01E05,A Fraud and a Hero,A Fraud and a Hero (S01E05) is the fifth episo...,8.94,10340.0,106.0,183.0,223.0,1.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414022,112801,2604421,2009-12-10T00:00,S01E22,Weapons,Weapons (S01E22) is the twenty-second episode ...,NaN,96.0,0.0,0.0,0.0,0.0,0.0,0.0
414023,112801,2604431,2009-12-17T00:00,S01E23,Unseen,Unseen (S01E23) is the twenty-third episode of...,NaN,97.0,0.0,0.0,0.0,0.0,0.0,0.0
414024,112801,2604441,2009-12-24T00:00,S01E24,Behind the Scenes,Behind the Scenes (S01E24) is the twenty-fourt...,NaN,96.0,0.0,0.0,0.0,0.0,0.0,0.0
414025,112801,2604451,2009-12-31T00:00,S01E25,Making of Alaska and South America,Making of Alaska and South America (S01E25) is...,NaN,94.0,0.0,0.0,0.0,0.0,0.0,0.0
414026,112801,2604471,2010-01-07T00:00,S01E26,Endangered,Endangered (S01E26) is the twenty-sixth episod...,NaN,94.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
merged_df = pd.merge(episode_df, tvshows_df, how="inner", left_on="show_id", right_on="id")
merged_df

,show_id,episode_id,time,episode,title,description,rating,times_watched,mood-good,mood-fun,mood-wow,mood-sad,mood-so-so,mood-bad,id,name,followers,nb_rates,runtime,number_of_seasons,network,mean_rate,poster_image,seasons
0,315103,5697528,2016-10-05T03:00,S01E01,Idiots with Numbers!,Idiots with Numbers! (S01E01) is the first epi...,9.48,12307.0,175.0,388.0,136.0,1.0,16.0,3.0,315103,Nanbaka,16617,620,25,2,MBS,4.57,https://dg31sz3gwrwan.cloudfront.net/poster/31...,"[{'number': 1, 'nb_episodes': 13}, {'number': ..."
1,315103,5774664,2016-10-12T03:00,S01E02,The Inmates Are Stupid! The Guards Are Kind of...,The Inmates Are Stupid! The Guards Are Kind of...,9.52,11423.0,156.0,349.0,82.0,0.0,5.0,3.0,315103,Nanbaka,16617,620,25,2,MBS,4.57,https://dg31sz3gwrwan.cloudfront.net/poster/31...,"[{'number': 1, 'nb_episodes': 13}, {'number': ..."
2,315103,5774665,2016-10-19T03:00,S01E03,Another Idiot Has Come!!,Another Idiot Has Come!! (S01E03) is the third...,9.36,11067.0,145.0,339.0,63.0,0.0,7.0,1.0,315103,Nanbaka,16617,620,25,2,MBS,4.57,https://dg31sz3gwrwan.cloudfront.net/poster/31...,"[{'number': 1, 'nb_episodes': 13}, {'number': ..."
3,315103,5774666,2016-10-26T03:00,S01E04,Happy New Year! The New Year's Tournament Is W...,Happy New Year! The New Year's Tournament Is W...,8.36,10552.0,134.0,270.0,109.0,0.0,3.0,3.0,315103,Nanbaka,16617,620,25,2,MBS,4.57,https://dg31sz3gwrwan.cloudfront.net/poster/31...,"[{'number': 1, 'nb_episodes': 13}, {'number': ..."
4,315103,5774667,2016-11-02T03:00,S01E05,A Fraud and a Hero,A Fraud and a Hero (S01E05) is the fifth episo...,8.94,10340.0,106.0,183.0,223.0,1.0,2.0,2.0,315103,Nanbaka,16617,620,25,2,MBS,4.57,https://dg31sz3gwrwan.cloudfront.net/poster/31...,"[{'number': 1, 'nb_episodes': 13}, {'number': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414022,112801,2604421,2009-12-10T00:00,S01E22,Weapons,Weapons (S01E22) is the twenty-second episode ...,NaN,96.0,0.0,0.0,0.0,0.0,0.0,0.0,112801,Deadly 60,233,16,30,3,BBC One,4.11,https://dg31sz3gwrwan.cloudfront.net/poster/11...,"[{'number': 1, 'nb_episodes': 26}, {'number': ..."
414023,112801,2604431,2009-12-17T00:00,S01E23,Unseen,Unseen (S01E23) is the twenty-third episode of...,NaN,97.0,0.0,0.0,0.0,0.0,0.0,0.0,112801,Deadly 60,233,16,30,3,BBC One,4.11,https://dg31sz3gwrwan.cloudfront.net/poster/11...,"[{'number': 1, 'nb_episodes': 26}, {'number': ..."
414024,112801,2604441,2009-12-24T00:00,S01E24,Behind the Scenes,Behind the Scenes (S01E24) is the twenty-fourt...,NaN,96.0,0.0,0.0,0.0,0.0,0.0,0.0,112801,Deadly 60,233,16,30,3,BBC One,4.11,https://dg31sz3gwrwan.cloudfront.net/poster/11...,"[{'number': 1, 'nb_episodes': 26}, {'number': ..."
414025,112801,2604451,2009-12-31T00:00,S01E25,Making of Alaska and South America,Making of Alaska and South America (S01E25) is...,NaN,94.0,0.0,0.0,0.0,0.0,0.0,0.0,112801,Deadly 60,233,16,30,3,BBC One,4.11,https://dg31sz3gwrwan.cloudfront.net/poster/11...,"[{'number': 1, 'nb_episodes': 26}, {'number': ..."
414026,112801,2604471,2010-01-07T00:00,S01E26,Endangered,Endangered (S01E26) is the twenty-sixth episod...,NaN,94.0,0.0,0.0,0.0,0.0,0.0,0.0,112801,Deadly 60,233,16,30,3,BBC One,4.11,https://dg31sz3gwrwan.cloudfront.net/poster/11...,"[{'number': 1, 'nb_episodes': 26}, {'number': ..."

In [7]:
us_network = pd.read_csv("Data/network_names.csv")
us_network

           USA Networks  Count of title
0                   A&E            1017
1                   ABC             461
2              ABC (US)            7843
3            ABC Family             512
4            Adult Swim             634
5                Amazon             998
6                   AMC             310
7         Animal Planet             488
8             Apple TV+              82
9                   BBC              99
10          BBC America              93
11             BBC Four             178
12              BBC One            2754
13            BBC Three             520
14              BBC Two            1464
15                  BET             451
16                Bravo             836
17      Cartoon Network            4721
18                  CBS            9075
19       Comedy Central            1080
20              CW Seed             148
21            Discovery            1298
22    Discovery Channel              62
23       Disney Channel            2803
24            Disney XD            1233
25              Disney+             227
26                   E!             707
27                   E4             259
28         Food Network             552
29                  FOX            4771
30                   FX             496
31     Hallmark Channel             255
32                  HBO            1768
33              History            1172
34                 Hulu             601
35             Lifetime             765
36                  MTV            1625
37  National Geographic             719
38                  NBC            8324
39              Netflix            5384
40          Nickelodeon            4147
41                  PBS            2661
42  Smithsonian Channel              36
43                 Syfy            1343
44               The CW            1111
45                  TLC            1259
46             TNT (US)             611
47          Toon Disney             522
48       Travel Channel             610
49          USA Network             849
50                  VH1             711
51       Warner Channel             119
52                WOWOW            1031
53          WWE Network             516

In [8]:
us_data = pd.merge(merged_df, us_network, how="inner", left_on="network", right_on="USA Networks")
us_data

,show_id,episode_id,time,episode,title,description,rating,times_watched,mood-good,mood-fun,mood-wow,mood-sad,mood-so-so,mood-bad,id,name,followers,nb_rates,runtime,number_of_seasons,network,mean_rate,poster_image,seasons,USA Networks,Count of title
0,79029,375789,2005-11-07T21:30,S01E01,Much Ado About Nothing,Much Ado About Nothing (S01E01) is the first e...,NaN,74.0,5.0,3.0,5.0,0.0,0.0,0.0,79029,ShakespeaRe-Told,242,8,120,1,BBC One,3.4,https://dg31sz3gwrwan.cloudfront.net/poster/79...,"[{'number': 1, 'nb_episodes': 4}]",BBC One,2754
1,79029,375790,2005-11-14T21:30,S01E02,Macbeth,Macbeth (S01E02) is the second episode of seas...,NaN,94.0,14.0,0.0,5.0,0.0,2.0,0.0,79029,ShakespeaRe-Told,242,8,120,1,BBC One,3.4,https://dg31sz3gwrwan.cloudfront.net/poster/79...,"[{'number': 1, 'nb_episodes': 4}]",BBC One,2754
2,79029,375791,2005-11-21T21:30,S01E03,The Taming of the Shrew,The Taming of the Shrew (S01E03) is the third ...,NaN,76.0,6.0,1.0,2.0,0.0,2.0,1.0,79029,ShakespeaRe-Told,242,8,120,1,BBC One,3.4,https://dg31sz3gwrwan.cloudfront.net/poster/79...,"[{'number': 1, 'nb_episodes': 4}]",BBC One,2754
3,79029,375792,2005-11-28T21:30,S01E04,A Midsummer Night's Dream,A Midsummer Night's Dream (S01E04) is the four...,NaN,66.0,4.0,0.0,0.0,0.0,4.0,0.0,79029,ShakespeaRe-Told,242,8,120,1,BBC One,3.4,https://dg31sz3gwrwan.cloudfront.net/poster/79...,"[{'number': 1, 'nb_episodes': 4}]",BBC One,2754
4,251999,4173236,2011-02-21T01:00,S01E01,The Mammy,The Mammy (S01E01) is the first episode of sea...,NaN,58.0,1.0,0.0,0.0,0.0,0.0,0.0,251999,Mrs. Brown's Boys,193,9,180,1,BBC One,3.0,https://d36rlb2fgh8cjd.cloudfront.net/default-...,"[{'number': 1, 'nb_episodes': 6}]",BBC One,2754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81534,252486,4183419,T21:00,S01E08,NaN,S01E08 is the eighth episode of season one of ...,NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,252486,Dual Survival,458,1,1,2,Discovery Channel,0.0,https://dg31sz3gwrwan.cloudfront.net/poster/25...,"[{'number': 1, 'nb_episodes': 10}, {'number': ...",Discovery Channel,62
81535,252486,4183421,T21:00,S01E09,NaN,"S01E09 is the ninth episode of season one of ""...",NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,252486,Dual Survival,458,1,1,2,Discovery Channel,0.0,https://dg31sz3gwrwan.cloudfront.net/poster/25...,"[{'number': 1, 'nb_episodes': 10}, {'number': ...",Discovery Channel,62
81536,252486,4183422,T21:00,S01E10,NaN,"S01E10 is the tenth episode of season one of ""...",NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,252486,Dual Survival,458,1,1,2,Discovery Channel,0.0,https://dg31sz3gwrwan.cloudfront.net/poster/25...,"[{'number': 1, 'nb_episodes': 10}, {'number': ...",Discovery Channel,62
81537,248584,4098218,2011-01-27T20:00,S01E01,Volume 1,Volume 1 (S01E01) is the first episode of sea...,NaN,38.0,3.0,0.0,0.0,0.0,0.0,0.0,248584,Time Paladin Sakura,167,6,25,1,Discovery Channel,3.0,https://dg31sz3gwrwan.cloudfront.net/poster/24...,"[{'number': 1, 'nb_episodes': 2}]",Discovery Channel,62
81538,248584,4098219,2011-02-24T20:00,S01E02,Volume 2,Volume 2 (S01E02) is the second episode of sea...,NaN,37.0,3.0,0.0,0.0,0.0,0.0,0.0,248584,Time Paladin Sakura,167,6,25,1,Discovery Channel,3.0,https://dg31sz3gwrwan.cloudfront.net/poster/24...,"[{'number': 1, 'nb_episodes': 2}]",Discovery Channel,62

In [9]:
us_data["network"].value_counts()

CBS                    9075
NBC                    8324
ABC (US)               7843
Netflix                5384
FOX                    4771
Cartoon Network        4721
Nickelodeon            3982
Disney Channel         2790
PBS                    2661
BBC One                2658
HBO                    1768
MTV                    1625
Syfy                   1343
BBC Two                1338
Discovery              1298
TLC                    1259
Disney XD              1180
History                1133
The CW                 1111
Comedy Central         1080
WOWOW                  1031
A&E                    1017
Amazon                  998
USA Network             849
Bravo                   836
Lifetime                765
National Geographic     719
VH1                     711
E!                      707
Adult Swim              634
TNT (US)                611
Hulu                    579
Food Network            544
Toon Disney             522
WWE Network             516
ABC Family              512
FX                      496
BBC Three               490
Animal Planet           488
ABC                     461
Travel Channel          454
BET                     451
AMC                     304
E4                      259
Hallmark Channel        255
Disney+                 227
CW Seed                 148
BBC Four                123
Warner Channel          119
BBC                      99
BBC America              93
Apple TV+                82
Discovery Channel        62
Smithsonian Channel      33
Name: network, dtype: int64

In [10]:
clean_us_data = us_data.drop(columns=['id', 'USA Networks', 'Count of title'])
clean_us_data

,show_id,episode_id,time,episode,title,description,rating,times_watched,mood-good,mood-fun,mood-wow,mood-sad,mood-so-so,mood-bad,name,followers,nb_rates,runtime,number_of_seasons,network,mean_rate,poster_image,seasons
0,79029,375789,2005-11-07T21:30,S01E01,Much Ado About Nothing,Much Ado About Nothing (S01E01) is the first e...,NaN,74.0,5.0,3.0,5.0,0.0,0.0,0.0,ShakespeaRe-Told,242,8,120,1,BBC One,3.4,https://dg31sz3gwrwan.cloudfront.net/poster/79...,"[{'number': 1, 'nb_episodes': 4}]"
1,79029,375790,2005-11-14T21:30,S01E02,Macbeth,Macbeth (S01E02) is the second episode of seas...,NaN,94.0,14.0,0.0,5.0,0.0,2.0,0.0,ShakespeaRe-Told,242,8,120,1,BBC One,3.4,https://dg31sz3gwrwan.cloudfront.net/poster/79...,"[{'number': 1, 'nb_episodes': 4}]"
2,79029,375791,2005-11-21T21:30,S01E03,The Taming of the Shrew,The Taming of the Shrew (S01E03) is the third ...,NaN,76.0,6.0,1.0,2.0,0.0,2.0,1.0,ShakespeaRe-Told,242,8,120,1,BBC One,3.4,https://dg31sz3gwrwan.cloudfront.net/poster/79...,"[{'number': 1, 'nb_episodes': 4}]"
3,79029,375792,2005-11-28T21:30,S01E04,A Midsummer Night's Dream,A Midsummer Night's Dream (S01E04) is the four...,NaN,66.0,4.0,0.0,0.0,0.0,4.0,0.0,ShakespeaRe-Told,242,8,120,1,BBC One,3.4,https://dg31sz3gwrwan.cloudfront.net/poster/79...,"[{'number': 1, 'nb_episodes': 4}]"
4,251999,4173236,2011-02-21T01:00,S01E01,The Mammy,The Mammy (S01E01) is the first episode of sea...,NaN,58.0,1.0,0.0,0.0,0.0,0.0,0.0,Mrs. Brown's Boys,193,9,180,1,BBC One,3.0,https://d36rlb2fgh8cjd.cloudfront.net/default-...,"[{'number': 1, 'nb_episodes': 6}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81534,252486,4183419,T21:00,S01E08,NaN,S01E08 is the eighth episode of season one of ...,NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,Dual Survival,458,1,1,2,Discovery Channel,0.0,https://dg31sz3gwrwan.cloudfront.net/poster/25...,"[{'number': 1, 'nb_episodes': 10}, {'number': ..."
81535,252486,4183421,T21:00,S01E09,NaN,"S01E09 is the ninth episode of season one of ""...",NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,Dual Survival,458,1,1,2,Discovery Channel,0.0,https://dg31sz3gwrwan.cloudfront.net/poster/25...,"[{'number': 1, 'nb_episodes': 10}, {'number': ..."
81536,252486,4183422,T21:00,S01E10,NaN,"S01E10 is the tenth episode of season one of ""...",NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,Dual Survival,458,1,1,2,Discovery Channel,0.0,https://dg31sz3gwrwan.cloudfront.net/poster/25...,"[{'number': 1, 'nb_episodes': 10}, {'number': ..."
81537,248584,4098218,2011-01-27T20:00,S01E01,Volume 1,Volume 1 (S01E01) is the first episode of sea...,NaN,38.0,3.0,0.0,0.0,0.0,0.0,0.0,Time Paladin Sakura,167,6,25,1,Discovery Channel,3.0,https://dg31sz3gwrwan.cloudfront.net/poster/24...,"[{'number': 1, 'nb_episodes': 2}]"
81538,248584,4098219,2011-02-24T20:00,S01E02,Volume 2,Volume 2 (S01E02) is the second episode of sea...,NaN,37.0,3.0,0.0,0.0,0.0,0.0,0.0,Time Paladin Sakura,167,6,25,1,Discovery Channel,3.0,https://dg31sz3gwrwan.cloudfront.net/poster/24...,"[{'number': 1, 'nb_episodes': 2}]"

In [11]:
clean_us_data.dtypes

show_id                int64
episode_id             int64
time                  object
episode               object
title                 object
description           object
rating               float64
times_watched        float64
mood-good            float64
mood-fun             float64
mood-wow             float64
mood-sad             float64
mood-so-so           float64
mood-bad             float64
name                  object
followers              int64
nb_rates               int64
runtime                int64
number_of_seasons      int64
network               object
mean_rate            float64
poster_image          object
seasons               object
dtype: object

In [28]:
display_df=clean_us_data.drop(columns=['show_id','episode_id','time','rating','times_watched','mood-good','mood-fun',
                                      'mood-wow','mood-sad','mood-so-so','mood-bad','description','nb_rates','seasons',
                                       'mean_rate', 'poster_image'])
display_df

,episode,title,name,followers,runtime,number_of_seasons,network
0,S01E01,Much Ado About Nothing,ShakespeaRe-Told,242,120,1,BBC One
1,S01E02,Macbeth,ShakespeaRe-Told,242,120,1,BBC One
2,S01E03,The Taming of the Shrew,ShakespeaRe-Told,242,120,1,BBC One
3,S01E04,A Midsummer Night's Dream,ShakespeaRe-Told,242,120,1,BBC One
4,S01E01,The Mammy,Mrs. Brown's Boys,193,180,1,BBC One
...,...,...,...,...,...,...,...
81534,S01E08,NaN,Dual Survival,458,1,2,Discovery Channel
81535,S01E09,NaN,Dual Survival,458,1,2,Discovery Channel
81536,S01E10,NaN,Dual Survival,458,1,2,Discovery Channel
81537,S01E01,Volume 1,Time Paladin Sakura,167,25,1,Discovery Channel
81538,S01E02,Volume 2,Time Paladin Sakura,167,25,1,Discovery Channel

In [38]:
new=display_df[display_df.runtime != 1]
new

,episode,title,name,followers,runtime,number_of_seasons,network
0,S01E01,Much Ado About Nothing,ShakespeaRe-Told,242,120,1,BBC One
1,S01E02,Macbeth,ShakespeaRe-Told,242,120,1,BBC One
2,S01E03,The Taming of the Shrew,ShakespeaRe-Told,242,120,1,BBC One
3,S01E04,A Midsummer Night's Dream,ShakespeaRe-Told,242,120,1,BBC One
4,S01E01,The Mammy,Mrs. Brown's Boys,193,180,1,BBC One
...,...,...,...,...,...,...,...
81524,S02E04,NaN,Gold Rush: Alaska,827,60,1,Discovery Channel
81525,S02E05,NaN,Gold Rush: Alaska,827,60,1,Discovery Channel
81526,S02E06,NaN,Gold Rush: Alaska,827,60,1,Discovery Channel
81537,S01E01,Volume 1,Time Paladin Sakura,167,25,1,Discovery Channel
81538,S01E02,Volume 2,Time Paladin Sakura,167,25,1,Discovery Channel

In [12]:
emotions_data=clean_us_data.drop(columns=['description', 'nb_rates', 'number_of_seasons', 'poster_image', 'mean_rate','time','runtime'])
emotions_data

,show_id,episode_id,episode,title,rating,times_watched,mood-good,mood-fun,mood-wow,mood-sad,mood-so-so,mood-bad,name,followers,network,seasons
0,79029,375789,S01E01,Much Ado About Nothing,NaN,74.0,5.0,3.0,5.0,0.0,0.0,0.0,ShakespeaRe-Told,242,BBC One,"[{'number': 1, 'nb_episodes': 4}]"
1,79029,375790,S01E02,Macbeth,NaN,94.0,14.0,0.0,5.0,0.0,2.0,0.0,ShakespeaRe-Told,242,BBC One,"[{'number': 1, 'nb_episodes': 4}]"
2,79029,375791,S01E03,The Taming of the Shrew,NaN,76.0,6.0,1.0,2.0,0.0,2.0,1.0,ShakespeaRe-Told,242,BBC One,"[{'number': 1, 'nb_episodes': 4}]"
3,79029,375792,S01E04,A Midsummer Night's Dream,NaN,66.0,4.0,0.0,0.0,0.0,4.0,0.0,ShakespeaRe-Told,242,BBC One,"[{'number': 1, 'nb_episodes': 4}]"
4,251999,4173236,S01E01,The Mammy,NaN,58.0,1.0,0.0,0.0,0.0,0.0,0.0,Mrs. Brown's Boys,193,BBC One,"[{'number': 1, 'nb_episodes': 6}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81534,252486,4183419,S01E08,NaN,NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,Dual Survival,458,Discovery Channel,"[{'number': 1, 'nb_episodes': 10}, {'number': ..."
81535,252486,4183421,S01E09,NaN,NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,Dual Survival,458,Discovery Channel,"[{'number': 1, 'nb_episodes': 10}, {'number': ..."
81536,252486,4183422,S01E10,NaN,NaN,76.0,0.0,0.0,0.0,0.0,0.0,0.0,Dual Survival,458,Discovery Channel,"[{'number': 1, 'nb_episodes': 10}, {'number': ..."
81537,248584,4098218,S01E01,Volume 1,NaN,38.0,3.0,0.0,0.0,0.0,0.0,0.0,Time Paladin Sakura,167,Discovery Channel,"[{'number': 1, 'nb_episodes': 2}]"
81538,248584,4098219,S01E02,Volume 2,NaN,37.0,3.0,0.0,0.0,0.0,0.0,0.0,Time Paladin Sakura,167,Discovery Channel,"[{'number': 1, 'nb_episodes': 2}]"

In [13]:
emotions_data.to_json('emotion_data.json')

In [14]:
emotions_data.to_csv('emotion_csv.csv')

In [15]:
clean_us_data.to_json('emotion_data.json')

In [16]:
top10= pd.read_csv("top15networks.csv")
top10

,Unnamed: 0,show_id,episode_id,episode,title,times_watched,mood-good,mood-fun,mood-wow,mood-sad,mood-so-so,mood-bad,name,followers,nb_rates,runtime,number_of_seasons,network,mean_rate,timeslot,year
0,0,79029,375789,S01E01,Much Ado About Nothing,74.0,5.0,3.0,5.0,0.0,0.0,0.0,ShakespeaRe-Told,242,8,120,1,BBC One,3.40,21:30,2005.0
1,1,79029,375790,S01E02,Macbeth,94.0,14.0,0.0,5.0,0.0,2.0,0.0,ShakespeaRe-Told,242,8,120,1,BBC One,3.40,21:30,2005.0
2,2,79029,375791,S01E03,The Taming of the Shrew,76.0,6.0,1.0,2.0,0.0,2.0,1.0,ShakespeaRe-Told,242,8,120,1,BBC One,3.40,21:30,2005.0
3,3,79029,375792,S01E04,A Midsummer Night's Dream,66.0,4.0,0.0,0.0,0.0,4.0,0.0,ShakespeaRe-Told,242,8,120,1,BBC One,3.40,21:30,2005.0
4,4,251999,4173236,S01E01,The Mammy,58.0,1.0,0.0,0.0,0.0,0.0,0.0,Mrs. Brown's Boys,193,9,180,1,BBC One,3.00,01:00,2011.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59576,59576,262184,4392610,S2008E03,The Last Enemy (3),21.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,4,PBS,0.19,22:00,2008.0
59577,59577,262184,4392611,S2008E04,The Last Enemy (4),21.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,4,PBS,0.19,22:00,2008.0
59578,59578,262184,4392612,S2008E05,The Last Enemy (5),21.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,4,PBS,0.19,22:00,2008.0
59579,59579,262184,4392613,S2008E06,God on Trial,19.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,4,PBS,0.19,22:00,2008.0
59580,59580,262184,4392614,S2008E07,Filth,19.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,4,PBS,0.19,22:00,2008.0

In [17]:
top10_networks=top10.drop(columns=['Unnamed: 0', 'number_of_seasons', 'timeslot'])
top10_networks

,show_id,episode_id,episode,title,times_watched,mood-good,mood-fun,mood-wow,mood-sad,mood-so-so,mood-bad,name,followers,nb_rates,runtime,network,mean_rate,year
0,79029,375789,S01E01,Much Ado About Nothing,74.0,5.0,3.0,5.0,0.0,0.0,0.0,ShakespeaRe-Told,242,8,120,BBC One,3.40,2005.0
1,79029,375790,S01E02,Macbeth,94.0,14.0,0.0,5.0,0.0,2.0,0.0,ShakespeaRe-Told,242,8,120,BBC One,3.40,2005.0
2,79029,375791,S01E03,The Taming of the Shrew,76.0,6.0,1.0,2.0,0.0,2.0,1.0,ShakespeaRe-Told,242,8,120,BBC One,3.40,2005.0
3,79029,375792,S01E04,A Midsummer Night's Dream,66.0,4.0,0.0,0.0,0.0,4.0,0.0,ShakespeaRe-Told,242,8,120,BBC One,3.40,2005.0
4,251999,4173236,S01E01,The Mammy,58.0,1.0,0.0,0.0,0.0,0.0,0.0,Mrs. Brown's Boys,193,9,180,BBC One,3.00,2011.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59576,262184,4392610,S2008E03,The Last Enemy (3),21.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,PBS,0.19,2008.0
59577,262184,4392611,S2008E04,The Last Enemy (4),21.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,PBS,0.19,2008.0
59578,262184,4392612,S2008E05,The Last Enemy (5),21.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,PBS,0.19,2008.0
59579,262184,4392613,S2008E06,God on Trial,19.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,PBS,0.19,2008.0
59580,262184,4392614,S2008E07,Filth,19.0,0.0,0.0,0.0,0.0,0.0,0.0,Masterpiece Contemporary,307,2,90,PBS,0.19,2008.0

In [18]:
top10_networks.to_json('top10_networks.json', orient = 'index')

In [23]:
top10_networks.to_json('top10_networks1.json', orient = 'records')

In [ ]:
test2.unstack(0).plot.bar(stacked=True, figsize=(15,10))
plt.ylabel('Total movie count base on budget');
plt.show()

In [29]:
display_df.to_json('show_display.json', orient = 'records')